// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.connector.stash.json;
/*
 {
         "text": "A pithy comment on a particular line within a file.",
         "anchor": {
             "line": 1,
             "lineType": "CONTEXT",
             "fileType": "FROM"
             "path": "path/to/file",
             "srcPath": "path/to/file"
         }
     }
 */

public class FileComment {
    private String text;
    private Anchor anchor;

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getText() {
        return this.text;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Anchor getAnchor() {
        return this.anchor;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setText(final String text) {
        this.text = text;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setAnchor(final Anchor anchor) {
        this.anchor = anchor;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FileComment)) return false;
        final FileComment other = (FileComment)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$text = this.getText();
        final java.lang.Object other$text = other.getText();
        if (this$text == null ? other$text != null : !this$text.equals(other$text)) return false;
        final java.lang.Object this$anchor = this.getAnchor();
        final java.lang.Object other$anchor = other.getAnchor();
        if (this$anchor == null ? other$anchor != null : !this$anchor.equals(other$anchor)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FileComment;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $text = this.getText();
        result = result * PRIME + ($text == null ? 0 : $text.hashCode());
        final java.lang.Object $anchor = this.getAnchor();
        result = result * PRIME + ($anchor == null ? 0 : $anchor.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "FileComment(text=" + this.getText() + ", anchor=" + this.getAnchor() + ")";
    }

    @java.beans.ConstructorProperties({"text", "anchor"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public FileComment(final String text, final Anchor anchor) {
        this.text = text;
        this.anchor = anchor;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public FileComment() {
    }
}