// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.engine;

import org.apache.commons.lang3.exception.ExceptionUtils;
import org.jetbrains.annotations.NotNull;
import pl.touk.sputnik.configuration.Configuration;
import pl.touk.sputnik.review.Review;
import pl.touk.sputnik.review.ReviewException;
import pl.touk.sputnik.review.ReviewProcessor;
import pl.touk.sputnik.review.ReviewResult;

public class ReviewRunner {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ReviewRunner.class);
    private static final long THOUSAND = 1000L;
    @NotNull
    private final Review review;

    public void review(@NotNull ReviewProcessor processor) {
        log.info("Review started for processor {}", processor.getName());
        long start = System.currentTimeMillis();
        ReviewResult reviewResult = null;
        try {
            reviewResult = processor.process(review);
        } catch (ReviewException e) {
            log.error("Processor {} error", processor.getName(), e);
            review.addProblem(processor.getName(), ExceptionUtils.getRootCauseMessage(e));
        }
        log.info("Review finished for processor {}. Took {} s", processor.getName(), (System.currentTimeMillis() - start) / THOUSAND);
        if (reviewResult == null) {
            log.warn("Review for processor {} returned empty review", processor.getName());
        } else {
            log.info("Review for processor {} returned {} violations", processor.getName(), reviewResult.getViolations().size());
            review.add(processor.getName(), reviewResult);
        }
    }

    @java.beans.ConstructorProperties({"review"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public ReviewRunner(final Review review) {
        this.review = review;
    }
}