// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.engine.visitor.score;

import org.jetbrains.annotations.NotNull;
import pl.touk.sputnik.engine.visitor.AfterReviewVisitor;
import pl.touk.sputnik.review.Review;

public class NoScore implements AfterReviewVisitor {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(NoScore.class);


    @Override
    public void afterReview(@NotNull Review review) {
        log.info("No score for review");
    }
}