// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.connector.stash;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SingleFileChanges {
    private final String filename;
    private final Map<Integer, ChangeDetails> changesMap = new HashMap<>();

    public void addChange(int line, ChangeType changeType, List<String> comments) {
        changesMap.put(line, new ChangeDetails(changeType, new ArrayList<>(comments)));
    }

    public ChangeType getChangeType(int line) {
        return changesMap.get(line).changeType;
    }

    public boolean containsComment(Integer line, String message) {
        return changesMap.containsKey(line) && changesMap.get(line).comments.contains(message);
    }

    public boolean containsChange(Integer line) {
        return changesMap.containsKey(line);
    }

    private static class ChangeDetails {
        private final ChangeType changeType;
        private final List<String> comments;

        @java.beans.ConstructorProperties({"changeType", "comments"})
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public ChangeDetails(final ChangeType changeType, final List<String> comments) {
            this.changeType = changeType;
            this.comments = comments;
        }
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    SingleFileChanges(final String filename) {
        this.filename = filename;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public static class SingleFileChangesBuilder {
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        private String filename;

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        SingleFileChangesBuilder() {
        }

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public SingleFileChangesBuilder filename(final String filename) {
            this.filename = filename;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public SingleFileChanges build() {
            return new SingleFileChanges(filename);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @javax.annotation.Generated("lombok")
        public java.lang.String toString() {
            return "SingleFileChanges.SingleFileChangesBuilder(filename=" + this.filename + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public static SingleFileChangesBuilder builder() {
        return new SingleFileChangesBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getFilename() {
        return this.filename;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SingleFileChanges)) return false;
        final SingleFileChanges other = (SingleFileChanges)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$filename = this.getFilename();
        final java.lang.Object other$filename = other.getFilename();
        if (this$filename == null ? other$filename != null : !this$filename.equals(other$filename)) return false;
        final java.lang.Object this$changesMap = this.changesMap;
        final java.lang.Object other$changesMap = other.changesMap;
        if (this$changesMap == null ? other$changesMap != null : !this$changesMap.equals(other$changesMap)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SingleFileChanges;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $filename = this.getFilename();
        result = result * PRIME + ($filename == null ? 0 : $filename.hashCode());
        final java.lang.Object $changesMap = this.changesMap;
        result = result * PRIME + ($changesMap == null ? 0 : $changesMap.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "SingleFileChanges(filename=" + this.getFilename() + ", changesMap=" + this.changesMap + ")";
    }
}