// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.connector.stash;

public class StashPatchset {
    public String pullRequestId;
    public String repositorySlug;
    public String projectKey;

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getPullRequestId() {
        return this.pullRequestId;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getRepositorySlug() {
        return this.repositorySlug;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getProjectKey() {
        return this.projectKey;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setPullRequestId(final String pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setRepositorySlug(final String repositorySlug) {
        this.repositorySlug = repositorySlug;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setProjectKey(final String projectKey) {
        this.projectKey = projectKey;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StashPatchset)) return false;
        final StashPatchset other = (StashPatchset)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$pullRequestId = this.getPullRequestId();
        final java.lang.Object other$pullRequestId = other.getPullRequestId();
        if (this$pullRequestId == null ? other$pullRequestId != null : !this$pullRequestId.equals(other$pullRequestId)) return false;
        final java.lang.Object this$repositorySlug = this.getRepositorySlug();
        final java.lang.Object other$repositorySlug = other.getRepositorySlug();
        if (this$repositorySlug == null ? other$repositorySlug != null : !this$repositorySlug.equals(other$repositorySlug)) return false;
        final java.lang.Object this$projectKey = this.getProjectKey();
        final java.lang.Object other$projectKey = other.getProjectKey();
        if (this$projectKey == null ? other$projectKey != null : !this$projectKey.equals(other$projectKey)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StashPatchset;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $pullRequestId = this.getPullRequestId();
        result = result * PRIME + ($pullRequestId == null ? 0 : $pullRequestId.hashCode());
        final java.lang.Object $repositorySlug = this.getRepositorySlug();
        result = result * PRIME + ($repositorySlug == null ? 0 : $repositorySlug.hashCode());
        final java.lang.Object $projectKey = this.getProjectKey();
        result = result * PRIME + ($projectKey == null ? 0 : $projectKey.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "StashPatchset(pullRequestId=" + this.getPullRequestId() + ", repositorySlug=" + this.getRepositorySlug() + ", projectKey=" + this.getProjectKey() + ")";
    }

    @java.beans.ConstructorProperties({"pullRequestId", "repositorySlug", "projectKey"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public StashPatchset(final String pullRequestId, final String repositorySlug, final String projectKey) {
        this.pullRequestId = pullRequestId;
        this.repositorySlug = repositorySlug;
        this.projectKey = projectKey;
    }
}