// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.review;

public class Comment {
    private final int line;
    private final String message;

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getLine() {
        return this.line;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getMessage() {
        return this.message;
    }

    @java.beans.ConstructorProperties({"line", "message"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Comment(final int line, final String message) {
        this.line = line;
        this.message = message;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "Comment(line=" + this.getLine() + ", message=" + this.getMessage() + ")";
    }
}