// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.review;

import org.jetbrains.annotations.NotNull;
import java.util.ArrayList;
import java.util.List;

public class ReviewResult {

    private final List<Violation> violations = new ArrayList<Violation>();

    public void add(@NotNull Violation violation) {
        violations.add(violation);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<Violation> getViolations() {
        return this.violations;
    }
}