// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.review;

public class Violation {
    private final String filenameOrJavaClassName;
    private final int line;
    private final String message;
    private final Severity severity;

    @java.beans.ConstructorProperties({"filenameOrJavaClassName", "line", "message", "severity"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Violation(final String filenameOrJavaClassName, final int line, final String message, final Severity severity) {
        this.filenameOrJavaClassName = filenameOrJavaClassName;
        this.line = line;
        this.message = message;
        this.severity = severity;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getFilenameOrJavaClassName() {
        return this.filenameOrJavaClassName;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getLine() {
        return this.line;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Severity getSeverity() {
        return this.severity;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "Violation(filenameOrJavaClassName=" + this.getFilenameOrJavaClassName() + ", line=" + this.getLine() + ", message=" + this.getMessage() + ", severity=" + this.getSeverity() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Violation)) return false;
        final Violation other = (Violation)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$filenameOrJavaClassName = this.getFilenameOrJavaClassName();
        final java.lang.Object other$filenameOrJavaClassName = other.getFilenameOrJavaClassName();
        if (this$filenameOrJavaClassName == null ? other$filenameOrJavaClassName != null : !this$filenameOrJavaClassName.equals(other$filenameOrJavaClassName)) return false;
        if (this.getLine() != other.getLine()) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$severity = this.getSeverity();
        final java.lang.Object other$severity = other.getSeverity();
        if (this$severity == null ? other$severity != null : !this$severity.equals(other$severity)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Violation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $filenameOrJavaClassName = this.getFilenameOrJavaClassName();
        result = result * PRIME + ($filenameOrJavaClassName == null ? 0 : $filenameOrJavaClassName.hashCode());
        result = result * PRIME + this.getLine();
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 0 : $message.hashCode());
        final java.lang.Object $severity = this.getSeverity();
        result = result * PRIME + ($severity == null ? 0 : $severity.hashCode());
        return result;
    }
}