// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.connector.gerrit;

public class GerritPatchset {
    private final String changeId;
    private final String revisionId;

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getChangeId() {
        return this.changeId;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getRevisionId() {
        return this.revisionId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GerritPatchset)) return false;
        final GerritPatchset other = (GerritPatchset)o;
        if (!other.canEqual((java.lang.Object)this)) return false;
        final java.lang.Object this$changeId = this.getChangeId();
        final java.lang.Object other$changeId = other.getChangeId();
        if (this$changeId == null ? other$changeId != null : !this$changeId.equals(other$changeId)) return false;
        final java.lang.Object this$revisionId = this.getRevisionId();
        final java.lang.Object other$revisionId = other.getRevisionId();
        if (this$revisionId == null ? other$revisionId != null : !this$revisionId.equals(other$revisionId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GerritPatchset;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $changeId = this.getChangeId();
        result = result * PRIME + ($changeId == null ? 0 : $changeId.hashCode());
        final java.lang.Object $revisionId = this.getRevisionId();
        result = result * PRIME + ($revisionId == null ? 0 : $revisionId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
        return "GerritPatchset(changeId=" + this.getChangeId() + ", revisionId=" + this.getRevisionId() + ")";
    }

    @java.beans.ConstructorProperties({"changeId", "revisionId"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public GerritPatchset(final String changeId, final String revisionId) {
        this.changeId = changeId;
        this.revisionId = revisionId;
    }
}