// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.review.locator;

import pl.touk.sputnik.configuration.BuildTool;
import pl.touk.sputnik.configuration.Configuration;
import pl.touk.sputnik.configuration.GeneralOption;
import static org.apache.commons.lang3.Validate.notBlank;

public class BuildDirLocatorFactory {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(BuildDirLocatorFactory.class);


    public static BuildDirLocator create(Configuration configuration) {
        String buildTool = configuration.getProperty(GeneralOption.BUILD_TOOL);
        notBlank(buildTool);
        switch (BuildTool.valueOf(buildTool.toUpperCase())) {
        case MAVEN: 
            return new MavenBuildDirLocator();
        
        case GRADLE: 
            return new GradleBuildFileLocator();
        
        default: 
            log.warn("Build tool " + buildTool + " not supported, using maven");
            return new MavenBuildDirLocator();
        
        }
    }
}