// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.engine.visitor;

import org.jetbrains.annotations.NotNull;
import pl.touk.sputnik.review.Comment;
import pl.touk.sputnik.review.Review;
import pl.touk.sputnik.review.ReviewFile;
import java.util.Iterator;

public class LimitCommentVisitor implements AfterReviewVisitor {
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(LimitCommentVisitor.class);
    private static final String MESSAGE_FORMAT = "Showing only first %d comments. %d comments are filtered out";
    private int maximumCount;

    @Override
    public void afterReview(@NotNull Review review) {
        if (review.getTotalViolationCount() <= maximumCount) {
            log.info("There are {} total violations for this review, which is below maximum comment count {}. No comments are filtered", review.getTotalViolationCount(), maximumCount);
            return;
        }
        log.info("There are {} total violations for this review, which is higher than maximum comment count {}. {} comments will be filtered out.", review.getTotalViolationCount(), maximumCount, review.getTotalViolationCount() - maximumCount);
        filterOutComments(review);
        addMessage(review);
    }

    private void filterOutComments(Review review) {
        int counter = 0;
        for (ReviewFile reviewFile : review.getFiles()) {
            Iterator<Comment> iterator = reviewFile.getComments().iterator();
            while (iterator.hasNext()) {
                iterator.next();
                counter++;
                if (counter > maximumCount) {
                    iterator.remove();
                }
            }
        }
    }

    private void addMessage(Review review) {
        review.getMessages().add(String.format(MESSAGE_FORMAT, maximumCount, review.getTotalViolationCount() - maximumCount));
    }

    @java.beans.ConstructorProperties({"maximumCount"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public LimitCommentVisitor(final int maximumCount) {
        this.maximumCount = maximumCount;
    }
}