// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.configuration;

public enum CliOption implements ConfigurationOption {
    CONF("cli.conf", "Configuration properties file", null),
    CHANGE_ID("cli.changeId", "Gerrit change id", null),
    REVISION_ID("cli.revisionId", "Gerrit revision id", null),
    PULL_REQUEST_ID("cli.pullRequestId", "Stash pull request id", null);
    private String key;
    private String description;
    private String defaultValue;

    public String getCommandLineParam() {
        return key.substring(4);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private CliOption(final String key, final String description, final String defaultValue) {
        this.key = key;
        this.description = description;
        this.defaultValue = defaultValue;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getKey() {
        return this.key;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getDefaultValue() {
        return this.defaultValue;
    }
}