// Generated by delombok at Wed Aug 05 13:49:19 CEST 2015
package pl.touk.sputnik.connector;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Supported connectors.
 */
public enum ConnectorType {
    GERRIT("gerrit"),
    STASH("stash");
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ConnectorType.class);
    
    /**
     * Name used in configuration file.
     */
    private final String name;

    ConnectorType(String name) {
        this.name = name;
    }

    @NotNull
    public static ConnectorType getValidConnectorType(@Nullable String connectorName) {
        for (ConnectorType connectorType : values()) {
            if (connectorType.getName().equals(connectorName)) {
                return connectorType;
            }
        }
        log.error(String.format("Given connector (%s) is not valid, returned default one!", connectorName));
        return GERRIT;
    }

    /**
     * Name used in configuration file.
     */
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getName() {
        return this.name;
    }
}